from __future__ import annotations

import datetime as _dt
import json
import os
from pathlib import Path

from .adapter_common import backup_file, hook_source_path, prune_backups, python_executable
from .manifest import Manifest

CLIENT_NAME = "opencode"
PLUGINS_DIR = Path.home() / ".config" / "opencode" / "plugins"

JS_TEMPLATE = """// managed-by: agent-hook · {name} · {ts}
// Source: {source}
// DO NOT EDIT — regenerated by agent-hook on install/sync.

import {{ spawnSync }} from "node:child_process";

const HOOK_NAME = {name_json};
const PYTHON = {python_json};
const HOOK_SCRIPT = {script_json};
const EVENTS = {events_json};
const MATCHERS = {matchers_json};

function matcherFn(tool) {{
  if (!MATCHERS || MATCHERS.length === 0) return true;
  return MATCHERS.some((re) => new RegExp(re).test(tool || ""));
}}

function callHook(event) {{
  const payload = JSON.stringify(event);
  const proc = spawnSync(PYTHON, [HOOK_SCRIPT], {{
    input: payload,
    encoding: "utf8",
    timeout: 15000,
  }});
  const blocked = proc.status === 2;
  let parsed = null;
  try {{
    parsed = proc.stdout ? JSON.parse(proc.stdout) : null;
  }} catch {{
    parsed = null;
  }}
  return {{
    blocked,
    rc: proc.status,
    stderr: (proc.stderr || "").trim(),
    payload: parsed,
  }};
}}

export const events = EVENTS;
export const name = HOOK_NAME;

export async function onPreToolUse({{ tool, parameters }}) {{
  if (!EVENTS.includes("PreToolUse")) return null;
  if (!matcherFn(tool)) return null;
  const res = callHook({{ event: "PreToolUse", tool, parameters }});
  if (res.blocked) {{
    return {{ block: true, reason: res.stderr || `hook ${{HOOK_NAME}} blocked` }};
  }}
  return res.payload;
}}

export async function onPostToolUse({{ tool, parameters, result }}) {{
  if (!EVENTS.includes("PostToolUse")) return null;
  if (!matcherFn(tool)) return null;
  return callHook({{ event: "PostToolUse", tool, parameters, result }}).payload;
}}

export async function onSessionStart(ctx) {{
  if (!EVENTS.includes("SessionStart")) return null;
  return callHook({{ event: "SessionStart", cwd: ctx?.cwd || process.cwd() }}).payload;
}}

export async function onStop(ctx) {{
  if (!EVENTS.includes("Stop")) return null;
  return callHook({{ event: "Stop", cwd: ctx?.cwd || process.cwd() }}).payload;
}}

export default {{
  name: HOOK_NAME,
  events: EVENTS,
  onPreToolUse,
  onPostToolUse,
  onSessionStart,
  onStop,
}};
"""


def _plugin_path(name: str) -> Path:
    return PLUGINS_DIR / f"agent-hook-{name}.js"


def install(m: Manifest) -> dict:
    if m.compatibility.get("opencode") != "native":
        raise ValueError(f"{m.name}: opencode compatibility is {m.compatibility.get('opencode')!r}; refusing install")
    PLUGINS_DIR.mkdir(parents=True, exist_ok=True)
    src = hook_source_path(m.name)
    if not src.exists():
        raise FileNotFoundError(f"hook source not found at {src}")
    plugin = _plugin_path(m.name)
    backup = backup_file(plugin)
    ts = _dt.datetime.now().isoformat(timespec="seconds")
    content = JS_TEMPLATE.format(
        name=m.name,
        ts=ts,
        source=str(src),
        name_json=json.dumps(m.name),
        python_json=json.dumps(python_executable()),
        script_json=json.dumps(str(src)),
        events_json=json.dumps(list(m.hook_events)),
        matchers_json=json.dumps(list(m.matchers)),
    )
    plugin.write_text(content, encoding="utf-8")
    prune_backups(plugin, keep=5)
    return {
        "client": CLIENT_NAME,
        "name": m.name,
        "plugin": str(plugin),
        "backup": str(backup) if backup else None,
    }


def uninstall(name: str) -> dict:
    plugin = _plugin_path(name)
    if not plugin.exists():
        return {"client": CLIENT_NAME, "name": name, "removed": False, "reason": "not-found"}
    first_line = plugin.read_text(encoding="utf-8").splitlines()[:1]
    if not first_line or "managed-by: agent-hook" not in first_line[0]:
        return {"client": CLIENT_NAME, "name": name, "removed": False, "reason": "not-managed-by-agent-hook"}
    backup = backup_file(plugin)
    plugin.unlink()
    return {"client": CLIENT_NAME, "name": name, "removed": True, "backup": str(backup) if backup else None}


def list_installed() -> list[dict]:
    if not PLUGINS_DIR.exists():
        return []
    out = []
    for p in sorted(PLUGINS_DIR.glob("agent-hook-*.js")):
        managed = False
        try:
            first = p.read_text(encoding="utf-8").splitlines()[:1]
            managed = bool(first and "managed-by: agent-hook" in first[0])
        except Exception:
            pass
        out.append({"name": p.stem.replace("agent-hook-", ""), "managed": managed, "plugin": str(p)})
    return out


def status_for(name: str) -> str:
    for row in list_installed():
        if row["name"] == name:
            return "managed" if row["managed"] else "external"
    return "absent"
