from __future__ import annotations

import datetime as _dt
import json
import os
import re
from pathlib import Path

from .adapter_common import backup_file, hook_source_path, prune_backups, python_executable
from .manifest import Manifest

CLIENT_NAME = "opencode"
PLUGINS_DIR = Path.home() / ".config" / "opencode" / "plugins"

JS_TEMPLATE = """// managed-by: agent-hook · {name} · {ts}
// Source: {source}
// DO NOT EDIT — regenerated by agent-hook on install/sync.
//
// This plugin bridges Claude Code style stdin/stdout/exit-2 Python hooks
// to opencode's plugin API (https://opencode.ai/docs/plugins/).
//
// Event mapping:
//   PreToolUse        -> tool.execute.before  (throw to block, exit 2 = block)
//   PostToolUse       -> tool.execute.after
//   SessionStart      -> event (session.created)
//   Stop              -> event (session.idle)
//   PreCompact        -> experimental.session.compacting
//   UserPromptSubmit  -> tui.prompt.append   (best effort)
//   Notification      -> event (session.idle)
//   SubagentStop      -> (no native opencode event; skipped)

import {{ spawnSync }} from "node:child_process";

const HOOK_NAME = {name_json};
const PYTHON = {python_json};
const HOOK_SCRIPT = {script_json};
const EVENTS = new Set({events_json});
const MATCHERS = {matchers_json};

function matcherFn(toolName) {{
  if (!MATCHERS || MATCHERS.length === 0) return true;
  const name = String(toolName || "");
  return MATCHERS.some((re) => {{
    try {{
      return new RegExp(re, "i").test(name);
    }} catch {{
      return name.toLowerCase().includes(re.toLowerCase());
    }}
  }});
}}

function callHook(eventPayload) {{
  let proc;
  try {{
    proc = spawnSync(PYTHON, [HOOK_SCRIPT], {{
      input: JSON.stringify(eventPayload),
      encoding: "utf8",
      timeout: 15000,
    }});
  }} catch (e) {{
    return {{ blocked: false, payload: null, stderr: String(e), rc: -1 }};
  }}
  const blocked = proc.status === 2;
  let payload = null;
  try {{
    payload = proc.stdout ? JSON.parse(proc.stdout) : null;
  }} catch {{ /* non-JSON stdout is fine */ }}
  return {{
    blocked,
    payload,
    stderr: (proc.stderr || "").trim(),
    rc: proc.status,
  }};
}}

function normalizeToolName(name) {{
  if (!name) return "";
  const s = String(name).toLowerCase();
  if (s === "write") return "Write";
  if (s === "edit") return "Edit";
  if (s === "multiedit") return "MultiEdit";
  if (s === "bash") return "Bash";
  if (s === "read") return "Read";
  return name;
}}

function pickFilePath(args) {{
  if (!args || typeof args !== "object") return null;
  for (const k of ["filePath", "file_path", "path"]) {{
    if (typeof args[k] === "string") return args[k];
  }}
  if (Array.isArray(args.edits)) {{
    for (const e of args.edits) {{
      if (e && typeof e === "object" && typeof e.filePath === "string") return e.filePath;
    }}
  }}
  return null;
}}

export const {plugin_name} = async (ctx) => {{
  return {{
    "tool.execute.before": async (input, output) => {{
      if (!EVENTS.has("PreToolUse")) return;
      const toolName = normalizeToolName(input?.tool);
      if (!matcherFn(toolName)) return;

      const params = (output && output.args) || {{}};
      const filePath = pickFilePath(params);
      const command = params.command;

      const event = {{
        tool: toolName,
        parameters: {{
          ...(filePath ? {{ filePath }} : {{}}),
          ...(typeof command === "string" ? {{ command }} : {{}}),
          ...(params.edits ? {{ edits: params.edits }} : {{}}),
        }},
      }};
      const res = callHook(event);
      if (res.blocked) {{
        const reason = res.stderr || (res.payload && res.payload.reason) || `hook ${{HOOK_NAME}} blocked this tool call`;
        throw new Error(reason);
      }}
    }},

    "tool.execute.after": async (input, output) => {{
      if (!EVENTS.has("PostToolUse")) return;
      const toolName = normalizeToolName(input?.tool);
      if (!matcherFn(toolName)) return;

      const params = (output && output.args) || {{}};
      const event = {{
        tool: toolName,
        parameters: params,
        result: output?.output,
      }};
      callHook(event);
    }},

    "experimental.session.compacting": async (input, output) => {{
      if (!EVENTS.has("PreCompact")) return;
      const cwd = (ctx && ctx.directory) || process.cwd();
      const res = callHook({{ event: "PreCompact", cwd, reason: "session-compacting" }});
      if (res.payload && Array.isArray(output.context) && typeof res.payload === "object") {{
        const note = JSON.stringify(res.payload, null, 2);
        output.context.push("## Agent_hook pre-compact snapshot\\n" + note);
      }}
    }},

    "event": async ({{ event }}) => {{
      if (!event || !event.type) return;

      if (EVENTS.has("SessionStart") && event.type === "session.created") {{
        callHook({{ event: "SessionStart", cwd: (ctx && ctx.directory) || process.cwd() }});
        return;
      }}
      if (EVENTS.has("Stop") && event.type === "session.idle") {{
        callHook({{ event: "Stop", cwd: (ctx && ctx.directory) || process.cwd() }});
        return;
      }}
      if (EVENTS.has("Notification") && event.type === "session.idle") {{
        callHook({{ event: "Notification", title: "opencode", message: "Session idle" }});
        return;
      }}
    }},
  }};
}};
"""


def _plugin_path(name: str) -> Path:
    return PLUGINS_DIR / f"agent-hook-{name}.js"


def _to_plugin_name(name: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", name)
    return "AgentHook_" + "".join(p[:1].upper() + p[1:].lower() for p in parts if p)


def install(m: Manifest) -> dict:
    if m.compatibility.get("opencode") != "native":
        raise ValueError(f"{m.name}: opencode compatibility is {m.compatibility.get('opencode')!r}; refusing install")
    PLUGINS_DIR.mkdir(parents=True, exist_ok=True)
    src = hook_source_path(m.name)
    if not src.exists():
        raise FileNotFoundError(f"hook source not found at {src}")
    plugin = _plugin_path(m.name)
    backup = backup_file(plugin)
    ts = _dt.datetime.now().isoformat(timespec="seconds")
    content = JS_TEMPLATE.format(
        name=m.name,
        ts=ts,
        source=str(src),
        plugin_name=_to_plugin_name(m.name),
        name_json=json.dumps(m.name),
        python_json=json.dumps(python_executable()),
        script_json=json.dumps(str(src)),
        events_json=json.dumps(list(m.hook_events)),
        matchers_json=json.dumps(list(m.matchers)),
    )
    plugin.write_text(content, encoding="utf-8")
    prune_backups(plugin, keep=5)
    return {
        "client": CLIENT_NAME,
        "name": m.name,
        "plugin": str(plugin),
        "backup": str(backup) if backup else None,
    }


def uninstall(name: str) -> dict:
    plugin = _plugin_path(name)
    if not plugin.exists():
        return {"client": CLIENT_NAME, "name": name, "removed": False, "reason": "not-found"}
    first_line = plugin.read_text(encoding="utf-8").splitlines()[:1]
    if not first_line or "managed-by: agent-hook" not in first_line[0]:
        return {"client": CLIENT_NAME, "name": name, "removed": False, "reason": "not-managed-by-agent-hook"}
    backup = backup_file(plugin)
    plugin.unlink()
    prune_backups(plugin, keep=5)
    return {"client": CLIENT_NAME, "name": name, "removed": True, "backup": str(backup) if backup else None}


def list_installed() -> list[dict]:
    if not PLUGINS_DIR.exists():
        return []
    out = []
    for p in sorted(PLUGINS_DIR.glob("agent-hook-*.js")):
        managed = False
        try:
            first = p.read_text(encoding="utf-8").splitlines()[:1]
            managed = bool(first and "managed-by: agent-hook" in first[0])
        except Exception:
            pass
        out.append({"name": p.stem.replace("agent-hook-", ""), "managed": managed, "plugin": str(p)})
    return out


def status_for(name: str) -> str:
    for row in list_installed():
        if row["name"] == name:
            return "managed" if row["managed"] else "external"
    return "absent"
